# Check out https://docs.codemagic.io/yaml/yaml/ for more information
# Please review and update values in curly braces

workflows:
    ios-flutter:
        name: iOS App with Flutter Module
        environment:
            vars:
                HOST_IOS_APP_DIR: "ios"
                XCODE_PROJECT: "Runner"
                XCODE_SCHEME: "Runner.xcscheme"
            xcode: edge
            cocoapods: default
            flutter: stable
        scripts:
            - |
                # test build
                cd ios
                xcodebuild build -list
                xcodebuild build -project "Runner.xcodeproj" -list
            - |
                # build Flutter module
                flutter packages get
                flutter build ios --no-codesign
            - |
                # build iOS project
                cd $HOST_IOS_APP_DIR
                xcodebuild build -project "$XCODE_PROJECT.xcodeproj" -scheme Runner -archivePath /$HOME/Library/Developer/Xcode/DerivedData/YourApp.xcarchive archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
                xcodebuild -exportArchive -archivePath /$HOME/Library/Developer/Xcode/DerivedData/YourApp.xcarchive -exportPath /$HOME/Library/Developer/Xcode/DerivedData -exportOptionsPlist Runner/ExportOptions.plist
        artifacts:
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
            - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.ipa
            - $HOME/Library/Developer/Xcode/DerivedData/*.ipa

        publishing:
            email:
                recipients:
                    - calleman.ekbjorn@hotmail.se